version: '3'

services:
  db: 
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=league
  
  web:
    build: EmperorsLeague/.
    expose: 
      - "8443"
    restart: unless-stopped
    environment:
      - SPRING_RABBITMQ_HOST=broker
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/league
    deploy:
      mode: replicated
      replicas: 1
  
  broker:
    image: rabbitmq

  rabbitmq:
    build: ServicioInterno/.
    environment:
      - SPRING_RABBITMQ_HOST=broker
    deploy:
      mode: replicated
      replicas: 1
  